server:
  port: 8080

#mysql
spring:
  datasource:
    url: jdbc:mysql://192.168.163.101:3306/EamonMysql?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#reids
  redis:
    host: 127.0.0.1
    port: 6379
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    password: